server:
  port: 8005


spring:
  datasource: # 数据源的相关配置
    driver-class-name: com.mysql.cj.jdbc.Driver       # mysql驱动
    url: jdbc:mysql://192.168.1.100:3306/hutb-news-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
  redis:
    database: 0
    host: 192.168.1.100
    port: 6379
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

cn:
  edu:
    hutb:
      website:
        domain: hutbnews.com

